services:
  pycudawatch:
    build: .
    container_name: pycudawatch
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./collector:/app/collector
      - ./dashboard:/app/dashboard
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
